models/products/views.py
import os

from flask import Blueprint, render_template, request, session, current_app as app
from flask import redirect, url_for

from common.decorators import login_required, login_required_to_login
from models.products.product import Product, get_product_by_id, add_score_to_product, delete_product
from models.ratings.rating import Rating, get_rating_by_both
from common.utils import redirect_previous_url, remove_starting_digits, get_sent_audio_file
from recommender.core import r
from emotion.speech.production import get_review_stars, get_emotion

product_blueprint = Blueprint("product", __name__)


@product_blueprint.route("<product_id>")
@login_required_to_login
def product(product_id):
    p = get_product_by_id(product_id)
    user_id = session['user_id']
    rating = get_rating_by_both(user_id, product_id)
    review = rating.review if rating else 0
    emotion = rating.emotion if rating else None
    similar_products = p.get_similar_products(9)
    similar_ratings = [ get_rating_by_both(user_id, p.id) for p in similar_products ]
    print(similar_products)
    img = os.path.basename(p.image)
    return render_template("product/product.html",
                        product=p,
                        img=img,
                        similar_products=similar_products,
                        similar_ratings=similar_ratings,
                        review=review,
                        emotion=emotion,
                        os=os,
                        zip=zip,
                        remove_starting_digits=remove_starting_digits)
    

@product_blueprint.route("/upload_review", methods=['GET', 'POST'])
def upload_review():
    if request.method == "POST":
        # get the audio file that is sent from product.html
        audio_file = get_sent_audio_file("fname")
        # retrieve review stars from text
        review_stars = float(get_review_stars(audio_file))
        # retrieve emotion from text
        emotion = get_emotion(audio_file, emotions=['sad', 'neutral', 'happy'])
        # get the user id from the session ( logged in )
        user_id = session['user_id']
        # get the product id from the form
        product_id = request.form['product_id']
        # add score to the corresponding product
        add_score_to_product(user_id, product_id, review_stars)
        # save the new review
        Rating(user_id=user_id, product_id=product_id, review=review_stars, emotion=emotion).save()
        # update recommender system matrices
        r.update_matrices()
        return str(review_stars) + "|" + emotion


@product_blueprint.route("/delete/<id>")
def delete(id):
    delete_product(id)
    return redirect_previous_url()

templates/product/product.html
{% extends "base.html" %}
{% block headcontent %}
<style>
.text-align {
  background: url("{{url_for('static', filename='img/star-rating-sprite.png')}}") repeat-x;
  font-size: 0;
  height: 21px;
  line-height: 0;
  overflow: hidden;
  text-indent: -999em;
  width: 110px;
}
.product_star_rating {
    background: url("{{url_for('static', filename='img/star-rating-sprite.png')}}") repeat-x;
    background-position: 0 100%;
    float: left;
    height: 21px;
    display:block;
    
}

.img-thumbnail {
    width: 50px;
    height: 50px;
    border: 0 none;
}

#product_review {
    {% if review %}
    width: {{(review / 5)*100}}%;
    {% else %}
    width: 0%;
    {% endif %}
}

#emotion-image {
    display: none;
}

.img-responsive {
    height: 500px;
}

{% for product, rating in zip(similar_products, similar_ratings) %}
#{{remove_starting_digits(product.id)}} {
    {% if rating %}
    width: {{((rating.review / 5)*100)}}%;
    {% else %}
    width: 0%;
    {% endif %}
}
{% endfor %}
</style>

{% endblock headcontent %}
{% block content %}
<div class="container">

    <div class="card mt-4">
        <img class="card-img-top img-fluid img-responsive" src="{{url_for('static', filename='img/products/{}'.format(img))}}" alt="">
        <div class="card-body">
            <h3 class="card-title">{{product.name}}</h3>
            <h4>${{product.price}}</h4>
            <p class="card-text">{{product.description}}</p>
            <span id="rating-text" class="text-info">
                Not rated
            </span>
            <div class="text-align"><span class="product_star_rating" id="product_review"></span></div>
            <br>
            <div>
                <span>Emotion:</span>
                <span id="emotion-text" class="text-muted">None</span>
                <img id='emotion-image' class='img-thumbnail'></img>
            </div>
            <span class="text-muted">Category: </span>
            <b class="text-primary text-capitalize">{{product.tags}}</b>
        </div>
    </div>
    <br>
    <h4 class="text-muted">Similar Products</h4>
    <br>
    <div class="row">

        {% for product in similar_products %}
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
                <a href="{{url_for('product.product', product_id=product.id)}}"><img class="card-img-top"
                        src="{{url_for('static', filename='img/products/{}'.format(os.path.basename(product.image)))}}"
                        alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{{url_for('product.product', product_id=product.id)}}">{{product.name}}</a>
                    </h4>
                    <h5>${{product.price}}</h5>
                    <p class="card-text">{{product.description}}</p>
                </div>
                <div class="card-footer">
                    <div class="text-align"><span class="product_star_rating" id="{{remove_starting_digits(product.id)}}"></span></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <script src="{{url_for('static', filename='js/jquery-3.3.1.min.js')}}"></script>
    <script>

        // some functions 
        function capitalizeFirstLetter(string) {
            return string.charAt(0).toUpperCase() + string.slice(1);
        }

        function setEmotion(emotion) {
            if(emotion == "neutral") {
                classname = "text-secondary";
                imageElement = "{{url_for('static', filename='img/emojis/neutral.png')}}";
            } else if(emotion == "angry") {
                classname = "text-danger";
                imageElement = "{{url_for('static', filename='img/emojis/anger.png')}}";
            } else if(emotion == "sad") {
                classname = "text-warning";
                imageElement = "{{url_for('static', filename='img/emojis/sadness.png')}}";
            } else if(emotion == "happy") {
                classname = "text-success";
                imageElement = "{{url_for('static', filename='img/emojis/happiness.png')}}";
            } else if(emotion == "ps") {
                classname = "text-primary";
                imageElement = "{{url_for('static', filename='img/emojis/surprise.png')}}";
            }
            $("#emotion-text").text(capitalizeFirstLetter(emotion));
            $("#emotion-text").attr("class", classname);
            $("#emotion-image").attr("src", imageElement);
            $("#emotion-image").css("display", "inline");
        }

        {% if review %}
        $("#rating-text").text({{ review }}.toFixed(2) + " Stars");
        {% endif %}

        {% if emotion %}
        setEmotion("{{emotion}}");
        {% endif %}

        navigator.mediaDevices.getUserMedia = navigator.mediaDevices.getUserMedia || navigator.mediaDevices.webkitGetUserMedia || navigator.mediaDevices.mozGetUserMedia || navigator.mediaDevices.msGetUserMedia;
        navigator.mediaDevices.getUserMedia({ audio: true }).then(stream => {
            // store streaming data chunks in array
            const chunks = [];
            // create media recorder instance to initialize recording
            const recorder = new MediaRecorder(stream);
            // function to be called when data is received
            recorder.ondataavailable = e => {
                // add stream data to chunks
                chunks.push(e.data);
                // if recorder is 'inactive' then recording has finished
                if (recorder.state == 'inactive') {
                    // convert stream data chunks to a 'webm' audio format as a blob
                    const blob = new Blob(chunks, { type: 'audio/wav' });
                    // send to server
                    var fd = new FormData();
                    fd.append("fname", "audio.wav");
                    fd.append("data", blob);
                    fd.append("product_id", "{{product.id}}")
                    $.ajax({
                        type: "POST",
                        url: "{{url_for('product.upload_review')}}",
                        data: fd,
                        cache: false,
                        processData: false,
                        contentType: false
                    }).done(function (data) {
                        data = data.split("|");
                        review_score = data[0];
                        emotion = data[1];
                        console.log("Review score: " + review_score);
                        console.log("Emotion: " + emotion)
                        // for review stars
                        $("#product_review").css("width", (review_score/5)*100 + "%");
                        $("#rating-text").text(parseFloat(review_score).toFixed(2) + " Stars");
                        // for emotion
                        setEmotion(emotion);
                    });
                }
            };
            // start recording with 0.1 second time between receiving 'ondataavailable' events
            recorder.start(100);

            // stop the recording after 4 seconds
            setTimeout(function(){
                recorder.stop();
            }, 4000);

        
        })
            

    </script>
</div>
<!-- /.col-lg-9 -->
{% endblock content %}