models/products/views.py
import os

from flask import Blueprint, render_template, request, session, current_app as app
from flask import redirect, url_for

from common.decorators import login_required, login_required_to_login
from models.products.product import Product, get_product_by_id, add_score_to_product, delete_product
from models.ratings.rating import Rating, get_rating_by_both
from common.utils import redirect_previous_url, remove_starting_digits, get_sent_audio_file
from recommender.core import r
from emotion.speech.production import get_review_stars, get_emotion

product_blueprint = Blueprint("product", __name__)


@product_blueprint.route("<product_id>")
@login_required_to_login
def product(product_id):
    p = get_product_by_id(product_id)
    user_id = session['user_id']
    rating = get_rating_by_both(user_id, product_id)
    review = rating.review if rating else 0
    emotion = rating.emotion if rating else None
    similar_products = p.get_similar_products(9)
    similar_ratings = [ get_rating_by_both(user_id, p.id) for p in similar_products ]
    print(similar_products)
    img = os.path.basename(p.image)
    return render_template("product/product.html",
                        product=p,
                        img=img,
                        similar_products=similar_products,
                        similar_ratings=similar_ratings,
                        review=review,
                        emotion=emotion,
                        os=os,
                        zip=zip,
                        remove_starting_digits=remove_starting_digits)
    

@product_blueprint.route("/upload_review", methods=['GET', 'POST'])
def upload_review():
    if request.method == "POST":
        # get the audio file that is sent from product.html
        audio_file = get_sent_audio_file("fname")
        # retrieve review stars from text
        review_stars = float(get_review_stars(audio_file))
        # retrieve emotion from text
        emotion = get_emotion(audio_file, emotions=['sad', 'neutral', 'happy'])
        # get the user id from the session ( logged in )
        user_id = session['user_id']
        # get the product id from the form
        product_id = request.form['product_id']
        # add score to the corresponding product
        add_score_to_product(user_id, product_id, review_stars)
        # save the new review
        Rating(user_id=user_id, product_id=product_id, review=review_stars, emotion=emotion).save()
        # update recommender system matrices
        r.update_matrices()
        return str(review_stars) + "|" + emotion


@product_blueprint.route("/delete/<id>")
def delete(id):
    delete_product(id)
    return redirect_previous_url()

models/users/views.py
from flask import Blueprint, render_template, request, session
from flask import redirect, url_for

from models.users.user import User, get_user_by_email, new_user, is_user_admin, get_user_fields, get_all_users, delete_user, edit_user, get_user_by_id
from models.users.user import get_user_ratings_joined_with_products, get_number_of_users
from models.products.product import Product, get_all_products, get_product_fields, get_number_of_products
from models.products.product import get_number_of_rated_products
from models.ratings.rating import get_all_ratings, get_rating_fields, get_number_of_ratings
import common.utils as utils
from common.decorators import login_required

import os

user_blueprint = Blueprint("user", __name__)

@user_blueprint.route("/login", methods=["POST", "GET"])
def login():
    if request.method == "GET":
        # first time coming to login page
        return render_template("user/login.html", error=False)
    elif request.method == "POST":
        # requested login
        email = request.form.get("email")
        password = request.form.get("password")
        user = User(email, password)
        user_data = user.valid()
        if user_data:
            # maybe add more than email later
            session['email'] = email
            session['user_id'] = user_data['id']
            session['name'] = user_data['name']
            user_type = user_data['type']
            if user_type == "admin":
                return redirect(url_for(".admin"))
            return redirect("/")
            # return utils.redirect_previous_url()
        else:
            # no user with this combo email:pw
            return render_template("user/login.html", error=True)


@user_blueprint.route("/new", methods=["POST", "GET"])
def register():
    if request.method == "GET":
        return render_template("user/register.html", error=False)
    elif request.method == "POST":
        email = request.form.get('email')
        if utils.email_valid(email) and not get_user_by_email(email):
            # login with same method (POST) and same values
            name = request.form.get("first_name") + " " + request.form.get("last_name")
            password = request.form.get("password")
            # tempo
            if email == "admin@admin.admin":
                user_type = "admin"
            else:
                user_type = "normal"
            user = User(email=email, name=name, password=password, type=user_type)
            user.save()
            return redirect(url_for(".login"), code=307)
        else:
            # either email not valid or already exists in db
            return render_template("user/register.html", error=True)


@user_blueprint.route("/profile")
def profile():
    user_id = session.get("user_id")
    if user_id is None:
        return utils.redirect_previous_url()
    user = get_user_by_id(user_id)
    fields, elements = get_user_ratings_joined_with_products(user_id)
    return render_template("user/profile.html",
                            user=user,
                            fields=fields,
                            elements=elements,
                            os=os,
                            len=len,
                            str=str)


@user_blueprint.route("/logout")
def logout():
    if session.get("user_id"):
        # logged in
        del session['email']
        del session['user_id']
        del session['name']
    return redirect(url_for('home'))

@user_blueprint.route("/delete/<id>")
@login_required
def delete(id):
    delete_user(id)
    return utils.redirect_previous_url()

### Below is for admin ###

@user_blueprint.route("/admin")
@login_required
def admin():
    n_products = get_number_of_products()
    n_users    = get_number_of_users()
    n_ratings  = get_number_of_ratings()
    n_rated_products = get_number_of_rated_products()
    return render_template("admin/index.html",
                            n_ratings=n_ratings,
                            n_products=n_products,
                            n_users=n_users,
                            n_rated_products=n_rated_products,
                            round=round)


@user_blueprint.route("/admin/users")
@login_required
def users():
    name = "User"
    description = "The table of data of users"
    headers = get_user_fields()
    items  = get_all_users(formalize=False)
    return render_template("admin/tables.html",
                            name=name,
                            description=description,
                            headers=headers,
                            items=items,
                            len=len,
                            str=str,
                            os=os)

@user_blueprint.route("/admin/products")
@login_required
def products():
    name = "Product"
    description = "The table of data of all available products"
    headers = get_product_fields()
    items = get_all_products(formalize=False)
    return render_template("admin/tables.html",
                            name=name,
                            description=description,
                            headers=headers,
                            items=items,
                            len=len,
                            str=str,
                            os=os)


@user_blueprint.route("/admin/ratings")
@login_required
def ratings():
    name = "Rating"
    description = "The table of all ratings done by users to products"
    headers = get_rating_fields()
    items = get_all_ratings(formalize=False)
    return render_template("admin/tables.html",
                            name=name,
                            description=description,
                            headers=headers,
                            items=items,
                            len=len,
                            str=str,
                            os=os)


@user_blueprint.route("/admin/new_product", methods=['GET', 'POST'])
@login_required
def add_product():
    optgroups = {
        "Fast food": ["pizza", "hamburger", "sandwich"],
        "Drinks": ["shakes_smoothies", "cocktails", "soda", "coffee"],
        "Pasteries & bakery food": ["pastry", "bakery"],
        "Sea Food": ["sushi", "fish_dish"],
        "Pasta": ["italian_pasta", "noodles"],
        "Dessert & Salad": ["fruit_salad", "ice_cream", "veggie_salad", "fruits"],
        "Dishes": ["middle_east_food", "asian_dishes"],
        "Meals": ["barbeque", "roast_food"]
    }
    if request.method == 'POST':
        name = request.form.get("name")
        description = request.form.get("description")
        price = request.form.get("price")
        tags = request.form.get("tags")
        image = utils.get_sent_image_file("img_file")
        product = Product(name=name,
                            description=description,
                            price=price,
                            tags=tags,
                            score=0,
                            image=image)
        product.save()
        message = f"Product: {name} Saved successfully"
    else:
        message = ""
    return render_template("admin/new_product.html", message=message, optgroups=optgroups)



templates/base.html
<!doctype html>
<html>

<head>
    <meta charset='utf-8'>
    <title>Food Shop</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/shop-homepage.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <!-- <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap-theme.min.css')}}"> -->

    {% block headcontent %}

    {% endblock headcontent %}
</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Food Shop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <a class="nav-item" href="{{url_for('user.admin')}}">Admin Page</a>
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Utilities
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                    <a href="{{url_for('test_speech')}}" class="dropdown-item">Test Speech</a>
                </div>
            </div>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('home')}}">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    {% if session['email'] %}
                    <li class="nav-item">
                        <a class="nav-link btn text-warning" href="{{url_for('recommended')}}">Recommended Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn" href="{{url_for('user.profile')}}">Profile</a>
                    </li>
                    {% endif %}
                    {% if not session['email'] %}
                    <li class="nav-item">
                        <a class="nav-link btn font-weight-bold" href="{{url_for('user.login')}}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn" href="{{url_for('user.register')}}">Register</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link btn" href="{{url_for('user.logout')}}">Logout</a>
                    </li>

                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link btn" href="#">About</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link btn" href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- Search form -->
        <form class="form-inline" method="GET" action="{{url_for('search')}}">
            <input class="form-control mr-sm-2" type="search" name="q" id="q" placeholder="Search" aria-label="Search">
            <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>
    {% block content %}

    {% endblock content %}
    <script>
        if (typeof jQuery == 'undefined') {
            document.write('<script src="{{url_for("static", filename="js/jquery-3.3.1.min.js")}}">' + '<' + '/script>');
        }
    </script>
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block headcontent %}
    <style>
    
        .carousel-img {
            width: 900px;
            height: 450px;
        }
        
        .text-align {
            background: url("{{url_for('static', filename='img/star-rating-sprite.png')}}") repeat-x;
            font-size: 0;
            height: 21px;
            line-height: 0;
            overflow: hidden;
            text-indent: -999em;
            width: 110px;
        }

        .product_star_rating {
            background: url("{{url_for('static', filename='img/star-rating-sprite.png')}}") repeat-x;
            background-position: 0 100%;
            float: left;
            height: 21px;
            display:block;        
        }

        {% for product, rating in zip(products, ratings) %}
        #{{remove_starting_digits(product.id)}} {
            {% if rating %}
            width: {{(rating.review / 5)*100}}%;
            {% else %}
            width: 0%;
            {% endif %}
        }
        {% endfor %}
 <!--this code is by anis : modify , the size of the img_home container  -->
.home_page1{
width :100px;
height :200px;
background: red;
}
.home_page2{
background : #;
height: 90%;
width: 270px;


}
.size_img{
display : block ;
width : 100%;
height: 210px;
}
.card_size{
height : 90%;
}
    </style>
    <script>
        $(function(){
            $("img").css("height", "40%");
        })
    </script>
    
{% endblock headcontent %}
{% block content %}

<!-- Page Content -->
<div class="container">

    <div class="row">
        <div class="col-lg-3">
            <h2 class="my-4">
                {% if category %}
                {{category.replace("_", " ").capitalize()}}
                {% else %}
                Categories
                {% endif %}
            </h2>
            <div class="list-group" id="list-tab" role="tablist">
                
                {% for tag, count in tags.items() %}
                {% if category == tag %}
                <a class="list-group-item list-group-item-action active" href="{{url_for('categories', category=tag)}}"
                    aria-controls="home">{{tag.replace("_", " ").capitalize()}}<span class="badge badge-secondary badge-pill">  {{count}}</span></a>
                    
                {% else %}
                <a class="list-group-item list-group-item-action" href="{{url_for('categories', category=tag)}}"
                    aria-controls="home">{{tag.replace("_", " ").capitalize()}}<span class="badge badge-primary badge-pill">  {{count}}</span></a>
                    
                {% endif %}
                {% endfor %}
            </div>
        </div>
        
        <!-- /.col-lg-3 -->
        <div class="col-lg-9">
            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for i in range(len(chosen_products)) %}
                    <li data-target="#carouselExampleIndicators" data-slide-to="{{i}}" class="active"></li>
                    {% endfor %}
                </ol>
                <div class="carousel-inner" role="listbox">
                    {% for i, product in enumerate(chosen_products) %}
                        {% if i == 0 %}
                        <div class="carousel-item active">
                        {% else %}
                        <div class="carousel-item">
                            {% endif %}
                            <a href="{{url_for('product.product', product_id=product.id)}}">
                                <img class="d-block img-fluid carousel-img"
                                    src="{{url_for('static', filename='img/products/{}'.format(os.path.basename(product.image)))}}"
                                    alt="slide">
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">
                    <!--lcool : gonna modify this code -->
                    {% for product in products %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100 home_page2">
                            <a href="{{url_for('product.product', product_id=product.id)}}"><img class="card-img-top size_img"
                                    src="{{url_for('static', filename='img/products/{}'.format(os.path.basename(product.image)))}}"
                                    alt=""></a>
                            <div class="card-body card_size">
                                <h4 class="card-title">
                                    <a href="{{url_for('product.product', product_id=product.id)}}" style="color:#004caf">{{product.name}}</a>
                                </h4>
                                <h5>${{product.price}}</h5>
                                <p class="card-text">{{product.description}}</p>
                            </div>
                            <div class="card-footer">
                                <div class="text-align"><span class="product_star_rating" id="{{remove_starting_digits(product.id)}}"></span></div>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <br>
                    <br>
                    <h4>No products available.</h4>
                    {% endfor %}

                </div>
                <!-- /.row -->

            </div>
            <!-- /.col-lg-9 -->

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Smart Recommandation Project 2019</p>
        </div>
        <!-- /.container -->
    </footer>

    {% endblock content %}
    </div>

templates/speech.html
{% extends "base.html" %}
{% block headcontent %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">

{% endblock headcontent %}
{% block content %}
    <button type="button" class="btn btn-success" id="startRecord" style="margin: 10px;">Start</button>
    <button type="button" class="btn btn-warning" id="stopRecord" style="margin: 10px;">Stop</button>
    <br>
    <script src="{{url_for('static', filename='js/jquery-3.3.1.min.js')}}"></script>
    <script>
        window.SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;

        const recognition = new SpeechRecognition();
        recognition.interimResults = true;

        var counter = 0;

        $("body").append($("<h5 style id='rec" + counter + "'></h5>"));

        recognition.addEventListener("result", function (e) {

            const transcript = e.results[0][0].transcript;
            const confidence = e.results[0][0].confidence;
            console.log(transcript + ": " + confidence);
            if (confidence > 0.5) {
                $("#rec" + counter).text(transcript);
            }
            // if it is final word of speech, add new paragraph for next speech
            if (e.results[0].isFinal) {
                counter++;
                $("body").append($("<h5 style id='rec" + counter + "'></h5>"));
            }
        });

        recognition.addEventListener("end", recognition.start);

        $("#startRecord").on("click", function () {
            recognition.start();
        });

        $("#stopRecord").on("click", function () {
            recognition.stop();
        });
    </script>
{% endblock content%}

templates/speech_keras.html
{% extends "base.html" %}

{% block content %}
    <button type="button" class="btn btn-success" id="startRecord" style="margin: 10px;">Start</button>
    <button type="button" class="btn btn-warning" id="stopRecord" style="margin: 10px;">Stop</button>
    <script src="{{url_for('static', filename='js/jquery-3.3.1.min.js')}}"></script>
    <script>
        function createAudioElement(blobUrl) {
            const downloadEl = document.createElement('a');
            downloadEl.style = 'display: block';
            downloadEl.innerHTML = 'download';
            downloadEl.download = 'audio.wav';
            downloadEl.href = blobUrl;
            const audioEl = document.createElement('audio');
            audioEl.controls = true;
            const sourceEl = document.createElement('source');
            sourceEl.src = blobUrl;
            sourceEl.type = 'audio/wav';
            audioEl.appendChild(sourceEl);
            document.body.appendChild(audioEl);
            document.body.appendChild(downloadEl);
        }
        $("#stopRecord").attr("disabled", true);
        $("#startRecord").click(function () {
            // disable button startRecord
            $("#startRecord").attr("disabled", true);
            // enable button stopRecord
            $("#stopRecord").attr("disabled", false);
            // request permission to access audio stream
            navigator.mediaDevices.getUserMedia = navigator.mediaDevices.getUserMedia || navigator.mediaDevices.webkitGetUserMedia || navigator.mediaDevices.mozGetUserMedia || navigator.mediaDevices.msGetUserMedia;
            var counter = 0;
            navigator.mediaDevices.getUserMedia({ audio: true }).then(stream => {
                // store streaming data chunks in array
                const chunks = [];
                // create media recorder instance to initialize recording
                const recorder = new MediaRecorder(stream);
                // function to be called when data is received
                recorder.ondataavailable = e => {
                    // add stream data to chunks
                    chunks.push(e.data);
                    // if recorder is 'inactive' then recording has finished
                    if (recorder.state == 'inactive') {
                        // create another media recorder
                        const recorder = new MediaRecorder(stream);
                        // convert stream data chunks to a 'webm' audio format as a blob
                        const blob = new Blob(chunks, { type: 'audio/wav' });
                        // convert blob to URL so it can be assigned to a audio src attribute
                        createAudioElement(URL.createObjectURL(blob));
                        // send to server
                        var fd = new FormData();
                        fd.append("fname", "audio.wav");
                        fd.append("data", blob);
                        $.ajax({
                            type: "POST",
                            url: "{{url_for('test_keras')}}",
                            //data: JSON.stringify(fd, null, "\t"),
                            data: fd,
                            cache: false,
                            // ²contentType: "application/json;charset=UTF-8"
                            //dataType: "json",
                            processData: false,
                            contentType: false
                        }).done(function (data) {
                            counter++;
                            $("body").append($("<h5 style id='rec" + counter + "'>" + data + "</h5>"));
                            console.log(data);
                        });
                    }
                };
                // start recording with 0.1 second time between receiving 'ondataavailable' events
                
                recorder.start(100);
                
                $("#stopRecord").click(function () {
                    $("#startRecord").attr("disabled", false);
                    recorder.stop();
                    $(this).attr("disabled", true);
                });

            }).catch(console.error);
        });
    </script>
{% endblock content %}
{% block headcontent %}
<!-- <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}"> -->
{% endblock headcontent %}

templates/speech_sphinx.html
{% extends "base.html" %}

{% block content %}
    <button type="button" class="btn btn-success" id="startRecord" style="margin: 10px;">Start</button>
    <button type="button" class="btn btn-warning" id="stopRecord" style="margin: 10px;">Stop</button>
    <script src="{{url_for('static', filename='js/jquery-3.3.1.min.js')}}"></script>
    <script>
        function createAudioElement(blobUrl) {
            const downloadEl = document.createElement('a');
            downloadEl.style = 'display: block';
            downloadEl.innerHTML = 'download';
            downloadEl.download = 'audio.wav';
            downloadEl.href = blobUrl;
            const audioEl = document.createElement('audio');
            audioEl.controls = true;
            const sourceEl = document.createElement('source');
            sourceEl.src = blobUrl;
            sourceEl.type = 'audio/wav';
            audioEl.appendChild(sourceEl);
            document.body.appendChild(audioEl);
            document.body.appendChild(downloadEl);
        }
        $("#stopRecord").attr("disabled", true);
        $("#startRecord").click(function () {
            // disable button startRecord
            $("#startRecord").attr("disabled", true);
            // enable button stopRecord
            $("#stopRecord").attr("disabled", false);
            // request permission to access audio stream
            navigator.mediaDevices.getUserMedia = navigator.mediaDevices.getUserMedia || navigator.mediaDevices.webkitGetUserMedia || navigator.mediaDevices.mozGetUserMedia || navigator.mediaDevices.msGetUserMedia;
            var counter = 0;
            navigator.mediaDevices.getUserMedia({ audio: true }).then(stream => {
                // store streaming data chunks in array
                const chunks = [];
                // create media recorder instance to initialize recording
                const recorder = new MediaRecorder(stream);
                // function to be called when data is received
                recorder.ondataavailable = e => {
                    // add stream data to chunks
                    chunks.push(e.data);
                    // if recorder is 'inactive' then recording has finished
                    if (recorder.state == 'inactive') {
                        // create another media recorder
                        const recorder = new MediaRecorder(stream);
                        // convert stream data chunks to a 'webm' audio format as a blob
                        const blob = new Blob(chunks, { type: 'audio/wav' });
                        // convert blob to URL so it can be assigned to a audio src attribute
                        createAudioElement(URL.createObjectURL(blob));
                        // send to server
                        var fd = new FormData();
                        fd.append("fname", "audio.wav");
                        fd.append("data", blob);
                        $.ajax({
                            type: "POST",
                            url: "{{url_for('test_hmm')}}",
                            //data: JSON.stringify(fd, null, "\t"),
                            data: fd,
                            cache: false,
                            // ²contentType: "application/json;charset=UTF-8"
                            //dataType: "json",
                            processData: false,
                            contentType: false
                        }).done(function (data) {
                            counter++;
                            $("body").append($("<h5 style id='rec" + counter + "'>" + data + "</h5>"));
                            console.log(data);
                        });
                    }
                };
                // start recording with 0.1 second time between receiving 'ondataavailable' events
                
                recorder.start(100);
                
                $("#stopRecord").click(function () {
                    $("#startRecord").attr("disabled", false);
                    recorder.stop();
                    $(this).attr("disabled", true);
                });

            }).catch(console.error);
        });
    </script>
{% endblock content %}
{% block headcontent %}
<!-- <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}"> -->
{% endblock headcontent %}