models/ratings/views.py
from flask import Blueprint
from models.ratings.rating import delete_rating
from common.utils import redirect_previous_url
rating_blueprint = Blueprint("rating", __name__)


@rating_blueprint.route("/delete/<id>")
def delete(id):
    delete_rating(id)
    return redirect_previous_url()

models/users/views.py
from flask import Blueprint, render_template, request, session
from flask import redirect, url_for

from models.users.user import User, get_user_by_email, new_user, is_user_admin, get_user_fields, get_all_users, delete_user, edit_user, get_user_by_id
from models.users.user import get_user_ratings_joined_with_products, get_number_of_users
from models.products.product import Product, get_all_products, get_product_fields, get_number_of_products
from models.products.product import get_number_of_rated_products
from models.ratings.rating import get_all_ratings, get_rating_fields, get_number_of_ratings
import common.utils as utils
from common.decorators import login_required

import os

user_blueprint = Blueprint("user", __name__)

@user_blueprint.route("/login", methods=["POST", "GET"])
def login():
    if request.method == "GET":
        # first time coming to login page
        return render_template("user/login.html", error=False)
    elif request.method == "POST":
        # requested login
        email = request.form.get("email")
        password = request.form.get("password")
        user = User(email, password)
        user_data = user.valid()
        if user_data:
            # maybe add more than email later
            session['email'] = email
            session['user_id'] = user_data['id']
            session['name'] = user_data['name']
            user_type = user_data['type']
            if user_type == "admin":
                return redirect(url_for(".admin"))
            return redirect("/")
            # return utils.redirect_previous_url()
        else:
            # no user with this combo email:pw
            return render_template("user/login.html", error=True)


@user_blueprint.route("/new", methods=["POST", "GET"])
def register():
    if request.method == "GET":
        return render_template("user/register.html", error=False)
    elif request.method == "POST":
        email = request.form.get('email')
        if utils.email_valid(email) and not get_user_by_email(email):
            # login with same method (POST) and same values
            name = request.form.get("first_name") + " " + request.form.get("last_name")
            password = request.form.get("password")
            # tempo
            if email == "admin@admin.admin":
                user_type = "admin"
            else:
                user_type = "normal"
            user = User(email=email, name=name, password=password, type=user_type)
            user.save()
            return redirect(url_for(".login"), code=307)
        else:
            # either email not valid or already exists in db
            return render_template("user/register.html", error=True)


@user_blueprint.route("/profile")
def profile():
    user_id = session.get("user_id")
    if user_id is None:
        return utils.redirect_previous_url()
    user = get_user_by_id(user_id)
    fields, elements = get_user_ratings_joined_with_products(user_id)
    return render_template("user/profile.html",
                            user=user,
                            fields=fields,
                            elements=elements,
                            os=os,
                            len=len,
                            str=str)


@user_blueprint.route("/logout")
def logout():
    if session.get("user_id"):
        # logged in
        del session['email']
        del session['user_id']
        del session['name']
    return redirect(url_for('home'))

@user_blueprint.route("/delete/<id>")
@login_required
def delete(id):
    delete_user(id)
    return utils.redirect_previous_url()

### Below is for admin ###

@user_blueprint.route("/admin")
@login_required
def admin():
    n_products = get_number_of_products()
    n_users    = get_number_of_users()
    n_ratings  = get_number_of_ratings()
    n_rated_products = get_number_of_rated_products()
    return render_template("admin/index.html",
                            n_ratings=n_ratings,
                            n_products=n_products,
                            n_users=n_users,
                            n_rated_products=n_rated_products,
                            round=round)


@user_blueprint.route("/admin/users")
@login_required
def users():
    name = "User"
    description = "The table of data of users"
    headers = get_user_fields()
    items  = get_all_users(formalize=False)
    return render_template("admin/tables.html",
                            name=name,
                            description=description,
                            headers=headers,
                            items=items,
                            len=len,
                            str=str,
                            os=os)

@user_blueprint.route("/admin/products")
@login_required
def products():
    name = "Product"
    description = "The table of data of all available products"
    headers = get_product_fields()
    items = get_all_products(formalize=False)
    return render_template("admin/tables.html",
                            name=name,
                            description=description,
                            headers=headers,
                            items=items,
                            len=len,
                            str=str,
                            os=os)


@user_blueprint.route("/admin/ratings")
@login_required
def ratings():
    name = "Rating"
    description = "The table of all ratings done by users to products"
    headers = get_rating_fields()
    items = get_all_ratings(formalize=False)
    return render_template("admin/tables.html",
                            name=name,
                            description=description,
                            headers=headers,
                            items=items,
                            len=len,
                            str=str,
                            os=os)


@user_blueprint.route("/admin/new_product", methods=['GET', 'POST'])
@login_required
def add_product():
    optgroups = {
        "Fast food": ["pizza", "hamburger", "sandwich"],
        "Drinks": ["shakes_smoothies", "cocktails", "soda", "coffee"],
        "Pasteries & bakery food": ["pastry", "bakery"],
        "Sea Food": ["sushi", "fish_dish"],
        "Pasta": ["italian_pasta", "noodles"],
        "Dessert & Salad": ["fruit_salad", "ice_cream", "veggie_salad", "fruits"],
        "Dishes": ["middle_east_food", "asian_dishes"],
        "Meals": ["barbeque", "roast_food"]
    }
    if request.method == 'POST':
        name = request.form.get("name")
        description = request.form.get("description")
        price = request.form.get("price")
        tags = request.form.get("tags")
        image = utils.get_sent_image_file("img_file")
        product = Product(name=name,
                            description=description,
                            price=price,
                            tags=tags,
                            score=0,
                            image=image)
        product.save()
        message = f"Product: {name} Saved successfully"
    else:
        message = ""
    return render_template("admin/new_product.html", message=message, optgroups=optgroups)



templates/user/login.html
{% extends "base.html" %}

{% block headcontent %}
<style type="text/css">
    body {
        /* color: #fff; */
		background: #63738a;
    }
	.login-form {
		width: 450px;
    	margin: 50px auto;
	}
    .login-form form {
    	margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
</style>
{% endblock headcontent %}
{% block content %}
    <br>
    <br>
    <br>
    <div class="login-form">
        <form action="{{url_for('user.login')}}" method="post">
            <h2 class="text-center">Log in</h2>
            {% if error %}
                <p class="text-danger">Some of the credentials isn't correct, try again please.</h4>
            {% endif %}
            <p class="text-warning">admin@admin.admin:admin is for admin dashboard</p>
            <div class="form-group">
                <input type="email" id="email" name="email" class="form-control" placeholder="Email" required="required">
            </div>
            <div class="form-group">
                <input type="password" id="password" name="password" class="form-control" placeholder="Password" required="required">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Log in</button>
            </div>
            <div class="clearfix">
                <label class="pull-left checkbox-inline"><input type="checkbox"> Remember me</label>
                <a href="#" class="pull-right">Forgot Password?</a>
            </div>        
        </form>
        <p class="text-center"><a href="{{url_for('user.register')}}">Create an Account</a></p>
    </div>

{% endblock content %}

templates/user/profile.html
{% extends "base.html" %}
{% block headcontent %}
<style>
    .img-fluid {
        max-width: 150px;
        max-height: 150px;
    }
</style>
{% endblock headcontent %}
{% block content %}
<div class="container">
    <h1 class="h3 mb-2 text-gray-800 text-capitalize">{{user.name}}</h1>
    <p class="mb-4">Total Product Ratings</p>
    <div class="card shadow mb-6">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Total: {{len(elements)}}</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            {% for attribute in fields[1:] %}
                            <th>{{attribute}}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            {% for attribute in fields[1:] %}
                            <th>{{attribute}}</th>
                            {% endfor %}
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for item in elements %}
                        <tr>
                            {% for att in item[1:] %}
                            {% if str(att).endswith('.png') or str(att).endswith('.jpeg') %}
                            <td><img class="img-fluid"
                                    src="{{url_for('static', filename='img/products/{}'.format(os.path.basename(att)))}}"><img>
                            </td>
                            {% else %}
                            <td>{{att}}</td>
                            {% endif %}
                            {% endfor %}
                            <td><a href="{{url_for('rating.delete', id=user.id + '*' + item[0])}}"
                                    class="btn btn-danger">Delete</a></td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/user/register.html
{% extends "base.html" %}
{% block headcontent %}
<style type="text/css">
	body{
		color: #fff;
		background: #63738a;
		/* font-family: 'Roboto', sans-serif; */
	}
    .form-control{
		height: 40px;
		box-shadow: none;
		color: #969fa4;
	}
	.form-control:focus{
		border-color: #5cb85c;
	}
    .form-control, .btn{        
        border-radius: 3px;
    }
	.signup-form{
		width: 500px;
		margin: 0 auto;
		padding: 30px 0;
	}
	.signup-form h2{
		color: #636363;
        margin: 0 0 15px;
		position: relative;
		text-align: center;
    }
	.signup-form h2:before, .signup-form h2:after{
		content: "";
		height: 2px;
		width: 30%;
		background: #d4d4d4;
		position: absolute;
		top: 50%;
		z-index: 2;
	}	
	.signup-form h2:before{
		left: 0;
	}
	.signup-form h2:after{
		right: 0;
	}
    .signup-form .hint-text{
		color: #999;
		margin-bottom: 30px;
		text-align: center;
	}
    .signup-form form{
		color: #999;
		border-radius: 3px;
    	margin-bottom: 15px;
        background: #f2f3f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
	.signup-form .form-group{
		margin-bottom: 20px;
	}
	.signup-form input[type="checkbox"]{
		margin-top: 3px;
	}
	.signup-form .btn{        
        font-size: 16px;
        font-weight: bold;		
		min-width: 140px;
        outline: none !important;
    }
	.signup-form .row div:first-child{
		padding-right: 10px;
	}
	.signup-form .row div:last-child{
		padding-left: 10px;
	}    	
    .signup-form a{
		color: #fff;
		text-decoration: underline;
	}
    .signup-form a:hover{
		text-decoration: none;
	}
	.signup-form form a{
		color: #5cb85c;
		text-decoration: none;
	}	
	.signup-form form a:hover{
		text-decoration: underline;
	}  
</style>
{% endblock headcontent %}
{% block content %}

    <div class="signup-form">
        <form action="{{url_for('user.register')}}" method="post">
            <h2>Register</h2>
            <p class="hint-text">Create your account. It's free and only takes a minute.</p>
            {% if error %}
                <p class="text-danger">Some of the credentials isn't correct, try again please.</h4>
            {% endif %}
            <div class="form-group">
                <div class="row">
                    <div class="col-xs-6"><input type="text" id="first_name" class="form-control" name="first_name" placeholder="First Name" required="required"></div>
                    <div class="col-xs-6"><input type="text" id="last_name" class="form-control" name="last_name" placeholder="Last Name" required="required"></div>
                </div>       	
            </div>
            <div class="form-group">
                <input type="email" id="email" class="form-control" name="email" placeholder="Email" required="required">
            </div>
            <div class="form-group">
                <input type="password" id="password" class="form-control" name="password" placeholder="Password" required="required">
            </div>
            <div class="form-group">
                <input type="password" id="confirm_password" class="form-control" name="confirm_password" placeholder="Confirm Password" required="required">
            </div>        
            <div class="form-group">
                <label class="checkbox-inline"><input type="checkbox" required="required"> I accept the <a href="#">Terms of Use</a> &amp; <a href="#">Privacy Policy</a></label>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success btn-lg btn-block">Register Now</button>
            </div>
        </form>
        <div class="text-center">Already have an account? <a href="{{url_for('user.login')}}">Sign in</a></div>
    </div>

{% endblock content %}